/*
 * Uniform.cpp
 *
 *  Created on: Nov 22, 2019
 * 	   Authors: Hoggett Emma <emma.hoggett@epfl.ch> &
 * 	            Vuillecard Pierre <pierre.vuillecard@epfl.ch>
 */

#include "Uniform.h"
#include <random>
#include <iostream>
#include <cmath>

// Constructor
Uniform :: Uniform(const double N) :mean_uniform(0.5) , var_uniform(1.0/12.0)
{

    try {
        set_size(N);
    }
    catch (Exception& err){
        err.PrintDebug();
        std::cout <<"Give alternative size \n";
        double N_new;
        std::cin >> N_new;
        set_size(N_new);
    }
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(0.0, 1.0);
    for (int n = 0; n < m_size; ++n) {
        // Use dis to transform the random unsigned int generated by gen into a
        // double in [0, 1). Each call to dis(gen) generates a new random double
        U_m.push_back(dis(gen));
    }
}

Uniform :: Uniform(double N, double a , double b ) : mean_uniform((a+b)/2.0) , var_uniform(pow(a+b,2)/12.0)
{
    try {
        set_size(N);
    }
    catch (Exception& err){
        err.PrintDebug();
        std::cout <<"Give alternative size \n";
        double N_new;
        std::cin >> N_new;
        set_size(N_new);
    }
    try {
        set_interval(a,b);
    }
    catch (Exception& err){
        err.PrintDebug();
        std::cout <<"Give alternative interval, the lower bound : \n";
        double new_a;
        std::cin >> new_a;
        double new_b;
        std::cin >> new_b;
        set_interval(new_a, new_b);
    }

    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(m_a, m_b);
    for (int n = 0; n < m_size; ++n) {
        // Use dis to transform the random unsigned int generated by gen into a
        // double in [0, 1). Each call to dis(gen) generates a new random double
        U_m.push_back(dis(gen));
    }

}




void Uniform::set_interval(const double a, const double b)
{
    if(a<b)
    {
        throw Exception("INPUT","The lower bound is less than the upper bound ");
    }
    else if(a==b)
    {
        throw Exception("INPUT","The lower bound can't be equal to the upper bound ");
    }
    else
    {
        m_a = a;
        m_b = b;
    }

}
void Uniform::set_size(const int N)
{
    if(N<0)
    {
        throw Exception("INPUT","The size must be positive");
    } else{
        m_size = N;
    }
}